### ISSUE TITLE
[Bug] Wyze deadbolt not working after latest ha-wyzeapi update

### ISSUE THREAD

**Issue by ljhardy** [SecKatie/ha-wyzeapi#690]
**Describe the bug**
After installing the last update and restarting HA, all of the wyze deadbolt entities are either "not provided" or "unavailable"

Battery - Not Provided
Lock - Unavailable

**To Reproduce**

Update the ha-wyzeapi to the latest version, restart ha.

**Expected behavior**

**System configuration**
System: HASS.IO
HA Version:  Core 2025.4.1
Supervisor 2025.03.4
Operating System 15.1
Frontend 20250404.0
WyzeApi Version: 0.1.3.3

**home-assistant.log**

This error originated from a custom integration.

Logger: custom_components.wyzeapi.coordinator
Source: helpers/update_coordinator.py:380
integration: Wyze Home Assistant Integration (documentation, issues)
First occurred: 10:11:05 AM (1 occurrences)
Last logged: 10:11:05 AM

Unexpected error fetching Wyze Lock State Updater data
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/client.py", line 214, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/dbus_fast/aio/message_bus.py", line 398, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/bleak_retry_connector/__init__.py", line 366, in establish_connection
    await client.connect(
    ...<3 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/habluetooth/wrappers.py", line 328, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/__init__.py", line 615, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/client.py", line 151, in connect
    async with async_timeout(timeout):
               ~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/timeouts.py", line 116, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/coordinator.py", line 54, in _async_update_data
    client = await self._get_ble_client()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/coordinator.py", line 157, in _get_ble_client
    self._bleak_client = await establish_connection(BleakClient, ble_device, ble_device.address)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak_retry_connector/__init__.py", line 390, in establish_connection
    _raise_if_needed(name, device.address, exc)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak_retry_connector/__init__.py", line 330, in _raise_if_needed
    raise BleakNotFoundError(msg) from exc
bleak_retry_connector.BleakNotFoundError: 70:54:64:FA:D2:65 - 70:54:64:FA:D2:65: Failed to connect after 7 attempt(s): TimeoutError

![Image](https://github.com/user-attachments/assets/813fb6bf-b11d-42d4-9a65-a80798b6d887)

**Comment by ejpenney** [comment]
I think this is a problem with the API, I just tried reverting to the old release, deleting and re-adding, my locks are all missing, with the same errors.

I don't know if something changed on the Wyze side or if it's a (temporary) issue but it's totally broken for me!

**Comment by ljhardy** [comment]
Same. I reverted to the last release and locks are still broken.

**Comment by ejpenney** [comment]
I just realized I'm getting a different error message than you:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 780, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/wyzeapi/token_manager.py", line 45, in inner_function
    await func(*args, **kwargs)
  File "/config/custom_components/wyzeapi/lock.py", line 165, in async_update
    lock = await self._lock_service.update(self._lock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wyzeapy/services/lock_service.py", line 24, in update
    device_info = await self._get_lock_info(lock)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wyzeapy/services/base_service.py", line 625, in _get_lock_info
    check_for_errors_lock(self, response_json)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wyzeapy/utils.py", line 112, in check_for_errors_lock
    raise UnknownApiError(response_json)
wyzeapy.exceptions.UnknownApiError: {'ReqID': '9e5767d0c2', 'ErrNo': '14003', 'ErrMsg': ' Internal Error'}
```

I also noticed I cannot control the locks via the Wyze app either. They also state "Internal Error" and won't even open the device. I tried restarting the lock and the device bridge, but no changes.

It's distinctly possible this is a different error and my issue appears to be a Wyze issue...

**Comment by ljhardy** [comment]
My locks work fine from the Wyze app, not there in Homeassistant.

**Comment by ljhardy** [comment]
I am also getting this error, although my locks are still working with the Wyze app:

wyzeapy.exceptions.UnknownApiError: {'ReqID': '9e5767d0c2', 'ErrNo': '14003', 'ErrMsg': ' Internal Error'}

**Comment by ljhardy** [comment]
@SecKatie - any ideas here?

**Comment by brg468** [comment]
@ljhardy if you roll back a version are your locks still broken? If you try that, post any related logs that come up please.

**Comment by ljhardy** [comment]
Yes, they are still broken with the previous version of the integration.  Do you want the logs from the current version or from -1?

**Comment by brg468** [comment]
I guess both if you can. Unless they’re the same.

**Comment by ljhardy** [comment]
Hmm.  It does appear that the locks are back with 0.1.32.  Except the entity names have changed a bit.  ( I wonder if that was my problem with 0.1.33 too ) I will reinstall that version and report back.

**Comment by ljhardy** [comment]
Ok, locks work with 0.1.32, but unavailable with 0.1.33.  Here are some debug log entries:

2025-04-14 15:58:06.139 DEBUG (MainThread) [custom_components.wyzeapi.light] Creating new WyzeApi light component
2025-04-14 15:58:06.142 DEBUG (MainThread) [custom_components.wyzeapi.switch] Creating new WyzeApi light component
2025-04-14 15:58:06.148 DEBUG (MainThread) [custom_components.wyzeapi.lock] Creating new WyzeApi lock component
2025-04-14 15:58:06.149 ERROR (MainThread) [custom_components.wyzeapi.coordinator] Unexpected error fetching Wyze Lock State Updater data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/coordinator.py", line 54, in _async_update_data
    client = await self._get_ble_client()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/coordinator.py", line 157, in _get_ble_client
    self._bleak_client = await establish_connection(BleakClient, ble_device, ble_device.address)
                                                                             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'address'
2025-04-14 15:58:06.151 DEBUG (MainThread) [custom_components.wyzeapi.coordinator] Finished fetching Wyze Lock State Updater data in 0.002 seconds (success: False)

**Comment by brg468** [comment]
Can you send me the model id? Its under the specific device page in HA on the top left under Device Info.

**Comment by ljhardy** [comment]
![Image](https://github.com/user-attachments/assets/f8d468ee-33e5-4d88-9412-2756278204be)

**Comment by ljhardy** [comment]
No, it's the deadbolt.  

![Image](https://github.com/user-attachments/assets/bc447276-11dc-4e6a-8c87-45afeff8c267)

**Comment by brg468** [comment]
Ok. I didn't realize that lock was supported at all prior to 0.1.33. Were you able to lock/unlock it from HA before or just see status? Also do you have Bluetooth setup on your HA installation?

**Comment by ljhardy** [comment]
Yes. It was fully functional. And yes, Bluetooth is configured on HA.

_______
Len Hardy
Bartlett, IL USA
________________________________

**Comment by brg468** [comment]
That's interesting. I was just reading through https://github.com/SecKatie/ha-wyzeapi/issues/394 and it didn't sound like it was controllable prior to it being added in the latest release. Not having this I can't really troubleshoot but maybe @widewing can share some insight since they wrote the latest PR to add Bluetooth functionality.

**Comment by widewing** [comment]
In previous version the states are fetched from cloud. The states were synced when your phone connected the lock, so you won't get the realtime update or control the lock. The current release connect the lock via bluetooth or [bluetooth proxy](https://esphome.io/components/bluetooth_proxy.html). But if you do not have bluetooth configured or your device is too far from lock, it will fail. Also it does not support the battery level yet, this requires more reverse engineer effort.

@brg468 I'm wondering if it would make sense to keep both approaches in this integration? To me it seems pointless to get the states from cloud since it's not synced and cannot control. but *maybe* to some users they still want to see the cloud data?

**Comment by ljhardy** [comment]
Hmm, so the host that HA is running on has to be close enough to the lock for bluetooth, or there has to be a bluetooth proxy configured in HA that is close enough to the lock?

**Comment by brg468** [comment]
> In previous version the states were fetched from cloud. The states were synced when your phone connected the lock, so you won't get the realtime update or control the lock. The current release connect the lock via bluetooth or [bluetooth proxy](https://esphome.io/components/bluetooth_proxy.html). But if you do not have bluetooth configured or your device is too far from lock, it will fail. Also it does not support the battery level yet, this requires more reverse engineer effort.

I was literally typing a similar explanation as you posted that 😄. 

My 2 cents would be to attempt to determine if the user is able to connect via Bluetooth at all, and if not continue with the old approach, or at least fail gracefully in the short term. Is there an easy way to check if Bluetooth is enabled on a HA install and add the lock or not based on that? 

Down the road we could maybe then figure out how to fall back to the old version of polled info if desired, and even consider a hybrid approach where battery status is polled on setups with Bluetooth enabled and get the rest of the info real-time over Bluetooth.

**Comment by ljhardy** [comment]
I happened to have an Atom Lite laying around, so I configured it with esphome  / bluetooth proxy and plugged it in a few feet from the deadbolt.  It does work!  Would be great to get the battery level in there somehow.  Thanks!

**Comment by widewing** [comment]
> > In previous version the states were fetched from cloud. The states were synced when your phone connected the lock, so you won't get the realtime update or control the lock. The current release connect the lock via bluetooth or [bluetooth proxy](https://esphome.io/components/bluetooth_proxy.html). But if you do not have bluetooth configured or your device is too far from lock, it will fail. Also it does not support the battery level yet, this requires more reverse engineer effort.
> 
> I was literally typing a similar explanation as you posted that 😄.
> 
> My 2 cents would be to attempt to determine if the user is able to connect via Bluetooth at all, and if not continue with the old approach, or at least fail gracefully in the short term. Is there an easy way to check if Bluetooth is enabled on a HA install and add the lock or not based on that?
> 
> Down the road we could maybe then figure out how to fall back to the old version of polled info if desired, and even consider a hybrid approach where battery status is polled on setups with Bluetooth enabled and get the rest of the info real-time over Bluetooth.

An underlying issue for hybrid states is the value may be inconsistent: if bluetooth is present but it cannot connect lock consistently, the state will jump between the real time value and cloud value, which could confuse people.

**Comment by brg468** [comment]
I guess my thought on the hybrid state would be more for things like battery that we just always pull from the server and always pull lock state from the lock if able.

**Comment by widewing** [comment]
> So far neither of my Lock Bolt locks have been able to lock/unlock even after the update. I have Bluetooth and Proxies around but honestly my be user error.. not sure if I need to pair it? anyways sharing my experience so far, I just hadn't had time to report.

It doesn't require pairing. Do they show lock/unlock states correctly? Can you share the relevant error logs

**Comment by bapesupreme** [comment]
I think all Wyze locks work via Bluetooth. Wyze lock gateway allows the locks to connect to WiFi. Maybe also zigbee? I can’t find the gateway for sale anywhere.

Anyone having issues should get a Bluetooth proxy or get the lock closer to your setup which must have Bluetooth.

I picked up a Bluetooth proxy and everything works now.

Unlocking, locking, reporting the state of the lock is slow but not unexpected because 1. Devices only connect via 2.4 2. It has to go from lock to gateway to my server 3. Wyzeapi probably gathers data from the cloud or app and relays it to the lock/my server

**Comment by bapesupreme** [comment]
With the Bluetooh Proxy, there is no reporting of the battery status. Not sure if this is normal.


Anyone else have the Wyze lock become unavailable multiple times during the day?
